# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from constants import globalConstants
from webdriver_manager.chrome import ChromeDriverManager 

class Testlogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get(globalConstants.URL)
    self.driver.maximize_window()
    WebDriverWait(self.driver,5).until(ec.visibility_of_element_located(By.XPATH,"/html/body/div[1]/header/div[2]/div[1]/a[2]" ))
    self.driver.find_element(By.XPATH, "/html/body/div[1]/header/div[2]/div[1]/a[2]").click()
    
    
